src/competition/urls.py
from django.conf.urls import patterns, url, include

from competition.views.competition_views import CompetitionListView
from competition.views.competition_views import CompetitionDetailView
from competition.views.team_views import TeamListView
from competition.views.team_views import FreeAgentListView
from competition.views.team_views import TeamDetailView
from competition.views.team_views import TeamCreationView
from competition.views.team_views import TeamLeaveView
from competition.views.team_views import TeamUpdateView
from competition.views.game_views import GameListView
from competition.views.game_views import GameDetailView
from competition.views.invitation_views import InvitationListView
from competition.views.invitation_views import InvitationDetailView
from competition.views.invitation_views import InvitationCreateView
from competition.views.invitation_views import InvitationAcceptView
from competition.views.invitation_views import InvitationDeclineView
from competition.views.registration_views import RegistrationView
from competition.views.registration_views import UnregisterView
from competition.api.api import TeamListAPIView
from competition.api.api import FreeAgentListAPIView


urlpatterns = patterns(
    "",

    # API Endpoints
    url(r'^api/competition/(?P<comp_slug>[\w-]+)/teams/',
        TeamListAPIView.as_view(),
        name='team_list_api'),
    url(r'^api/competition/(?P<comp_slug>[\w-]+)/freeagents/',
        FreeAgentListAPIView.as_view(),
        name='freeagent_list_api'),

    # Competition Views
    url(r'^competition/$',
        CompetitionListView.as_view(),
        name='competition_list'),
    url(r'^competition/(?P<comp_slug>[\w-]+)/$',
        CompetitionDetailView.as_view(),
        name='competition_detail'),

    # Team Views
    url(r'^competition/(?P<comp_slug>[\w-]+)/freeagents/$',
        FreeAgentListView.as_view(),
        name='freeagent_list'),
    url(r'^competition/(?P<comp_slug>[\w-]+)/teams/$',
        TeamListView.as_view(),
        name='team_list'),
    url(r'^competition/(?P<comp_slug>[\w-]+)/team/(?P<slug>[\w-]+)/$',
        TeamDetailView.as_view(),
        name='team_detail'),
    url(r'^competition/(?P<comp_slug>[\w-]+)/team-create/$',
        TeamCreationView.as_view(),
        name='team_create'),
    url(r'^competition/(?P<comp_slug>[\w-]+)/team-leave/$',
        TeamLeaveView.as_view(),
        name='team_leave'),
    url(r'^competition/(?P<comp_slug>[\w-]+)/team/(?P<slug>[\w-]+)/update/$',
        TeamUpdateView.as_view(),
        name='team_update'),

    # Registration Views
    url(r'^competition/(?P<comp_slug>[\w-]+)/register/$',
        RegistrationView.as_view(),
        name='register_for'),

    url(r'^competition/(?P<comp_slug>[\w-]+)/unregister/$',
        UnregisterView.as_view(),
        name='unregister_for'),

    # Game Views
    url(r'^competition/(?P<comp_slug>[\w-]+)/games/$',
        GameListView.as_view(),
        name='game_list'),
    url(r'^competition/(?P<comp_slug>[\w-]+)/game/(?P<pk>\d+)/$',
        GameDetailView.as_view(),
        name='game_detail'),

    # Invitation Views
    url(r'^invitations/$',
        InvitationListView.as_view(),
        name='invitation_list'),
    url(r'^invitations/invite/$',
        InvitationCreateView.as_view(),
        name='invitation_create'),
    url(r'^invitations/(?P<pk>\d+)/$',
        InvitationDetailView.as_view(),
        name='invitation_detail'),
    url(r'^invitations/(?P<pk>\d+)/accept$',
        InvitationAcceptView.as_view(),
        name='invitation_accept'),
    url(r'^invitations/(?P<pk>\d+)/decline$',
        InvitationDeclineView.as_view(),
        name='invitation_decline'),
)

src/competition/models/game_model.py
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models import Max

from competition.models.competition_model import Competition
from competition.models.team_model import Team

import json


class Game(models.Model):
    """Game Model

    To store additional game data, serialize it as a JSON string and
    store it in the extra_data field. If you want the data to be
    available to the user, include it under the "display" key like so:

    {"display": {"location": "place"},
     "referee": "tim"}

    If this information was the extra_data for an object, "location"
    would be displayed for the user, but "referee" would remain hidden.
    """
    class Meta:
        app_label = 'competition'
        unique_together = (
            ('game_id','competition'),
        )
        ordering = ['-game_id']
        get_latest_by = 'game_id'

    competition = models.ForeignKey(Competition)
    game_id = models.IntegerField(null=True, blank=True, default=None)

    created = models.DateTimeField(auto_now_add=True, null=True)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    status = models.CharField(blank=True, max_length=100)

    teams = models.ManyToManyField(Team, through='GameScore')

    # Default to JSON null, which gets loaded as None
    extra_data = models.TextField(null=True, default="null")

    def __unicode__(self):
        return "Game #%d" % self.id

    def save(self,*args,**kwargs):
        if self.game_id == None:
            q = Game.objects.filter(competition=self.competition)
            if not q.exists():
                self.game_id = 1
            else:
                self.game_id = q.aggregate(m=Max('game_id'))['m']+1
        super(Game,self).save(*args,**kwargs)

    def clean(self):
        if self.start_time and self.end_time and  self.start_time > self.end_time:
            raise ValidationError("Start time is after end time.")
        try:
            if self.extra_data:
                json.loads(self.extra_data)
        except ValueError:
            raise ValidationError("Invalid JSON string.")

    @models.permalink
    def get_absolute_url(self):
        return ('game_detail', (), {'pk': self.pk,
                                    'comp_slug': self.competition.slug})

    @property
    def data(self):
        return json.loads(self.extra_data)


class GameScore(models.Model):
    """
    This is a many to many relation with extra data to score the score
    of a matchup.
    """
    class Meta:
        app_label = 'competition'

    game = models.ForeignKey(Game, related_name="scores")
    team = models.ForeignKey(Team)
    score = models.IntegerField(null=True)

    #Default field for extra data for just this match participant.
    extra_data = models.TextField(null=True,default="null")

    def __unicode__(self):
        return "Game #{} Team: {} Score {}".format(self.game.pk,
                                                   self.team.name,
                                                   self.score)

    def clean(self):
        try:
            if self.extra_data:
                json.loads(self.extra_data)
        except ValueError:
            raise ValidationError("Invalid JSON string.")

    @models.permalink
    def get_absolute_url(self):
        return ('game_detail', (), {'pk': self.game.pk,
                                    'comp_slug': self.game.competition.slug})

    @property
    def data(self):
        return json.loads(self.extra_data)

src/competition/views/competition_views.py
from django.views.generic import ListView, DetailView
from django.core.exceptions import ObjectDoesNotExist

from competition.models.competition_model import Competition


class CompetitionListView(ListView):
    """Lists every single competition"""
    context_object_name = 'competitions'
    model = Competition
    template_name = 'competition/competition/competition_list.html'
    paginate_by = 10


class CompetitionDetailView(DetailView):
    """Shows details about a particular competition"""
    context_object_name = 'competition'
    model = Competition
    slug_url_kwarg = 'comp_slug'
    template_name = 'competition/competition/competition_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CompetitionDetailView, self).get_context_data(**kwargs)
        competition = self.object
        user = self.request.user
        context['user_registered'] = competition.is_user_registered(user)
        context['user_team'] = None
        try:
            if not user.is_anonymous():
                context['user_team'] = competition.team_set.get(members=user.pk)
        except ObjectDoesNotExist:
            pass
        return context

src/competition/templates/competition/competition/_competition_detail.html
{% load competition_tags %}

<table class="table table-condensed table-hover table-border">
  <thead>
  </thead>

  <tbody>
    <tr>
      <th>Starting Time</th>
      <td>{{ competition.start_time }}</td>
    </tr>
    <tr>
      <th>Ending Time</th>
      <td>{{ competition.end_time }}</td>
    </tr>
    <tr>
      <th>Is open?</th>
      <td>
        <span class="label label-{% if competition.is_open %}success{% else %}danger{% endif %}">
          {{ competition.is_open|yesno:"Yep!,Nope.," }}
        </span>
      </td>
    </tr>
    <tr>
      <th>Is running?</th>
      <td>
        <span class="label label-{% if competition.is_running %}success{% else %}danger{% endif %}">
          {{ competition.is_running|yesno:"Yep!,Nope.," }}
        </span>
      </td>
    </tr>
    <tr>
      {% if competition.payment_option == competition.PER_PERSON_PAYMENT %}
        <th>Cost per person:</th>
      {% endif %}
      {% if competition.payment_option == competition.PER_TEAM_PAYMENT %}
        <th>Cost per team:</th>
      {% endif %}
      <td>${{ competition.cost|floatformat:2 }}</td>
    </tr>
    {% if competition.min_num_team_members == competition.max_num_team_members %}
      <tr>
        <th>Team size</th>
        <td>{{ competition.min_num_team_members }}</td>
      </tr>
    {% else %}
      <tr>
        <th>Minimum team size</th>
        <td>{{ competition.min_num_team_members }}</td>
      </tr>
      <tr>
        <th>Maximum team size</th>
        <td>{{ competition.max_num_team_members }}</td>
      </tr>
    {% endif %}
      <tr>
        <th>Number of registered competitors</th>
        <td>{% registered_users_count competition %}</td>
      </tr>
  </tbody>
</table>

src/competition/templates/competition/competition/_sidebar.html
<ul id="competition-nav" class="nav nav-pills nav-stacked">
  <li>
    <a href="{% url 'competition_detail' competition.slug %}">
      <i class="fa fa-newspaper-o"></i>
      Competition Details
    </a>
  </li>
  {% if competition.is_running and user_team %}
  <li>
    <a href="{% url 'game_list' competition.slug %}">
      <i class="fa fa-flag"></i>
      Games
    </a>
  </li>
  {% endif %}
</ul>

src/competition/templates/competition/competition/competition_detail.html
{% extends "competition/competition_base_sidebar.html" %}

{% block page-header %}
  <div class="page-header" style="margin-top:20px;">
    <div class="row">
      <div id="name" class="col-sm-9 col-md-9">
        <h1>{{ competition.name }}</h1>
      </div>
    </div>
    <p style="font-size:16px;">
      <i>{{ competition.description }}</i>
    </p>
  </div>
{% endblock %}

{% block competition_content %}
  <div class="row">
    {% if competition.image %}
      <div id="avatar" class="col-sm-6 col-md-6">
          <img src="{{ competition.image.url }}" class="img-polaroid" alt="{{ competition.name }}" style="width:100%">
      </div>
    {% endif %}
    <div class="col-sm-{% if competition.image %}6{% else %}12{% endif %}
                col-md-{% if competition.image %}6{% else %}12{% endif %}">
      <h2>Details</h2>
      {% include "competition/competition/_competition_detail.html" %}
      {% if user.is_authenticated and competition.is_open and not user_team %}
        <p class="text-info text-center">
          <span class="label label-info">Heads up</span>
          You must be on a team to access competition code. Be
          sure to join one!
        </p>
      {% endif %}
    </div>
  </div>
{% endblock %}

src/competition/templates/competition/competition/competition_detail.inc.html
<table class="table table-striped">
  <thead>
  </thead>

  <tbody>
    <tr>
      <th>Starting Time</th>
      <td>{{ competition.start_time }}</td>
    </tr>
    <tr>
      <th>Ending Time</th>
      <td>{{ competition.end_time }}</td>
    </tr>
    <tr>
      <th>Is open?</th>
      <td>{{ competition.is_open }}</td>
    </tr>
    <tr>
      <th>Is running?</th>
      <td>{{ competition.is_running }}</td>
    </tr>
    <tr>
      <th>Cost per person:</th>
      <td>${{ competition.cost_per_person|floatformat:2 }}</td>
    </tr>
    <tr>
      <th>Minimum team size</th>      
      <td>{{ competition.min_num_team_members }}</td>      
    </tr>
    <tr>
      <th>Maximum team size</th>      
      <td>{{ competition.max_num_team_members }}</td>      
    </tr>
  </tbody>
</table>

src/competition/templates/competition/competition/competition_list.html
{% extends "competition/competition_base_plain.html" %}
{% load competition_tags %}

{% block page-header %}
  <div class="page-header">
    <h1>Competitions</h1>
  </div>
{% endblock %}

{% block competition_content %}
    {% for competition in competitions %}
      <div class="well">
        <div class="row">
          <div class="col-xs-12 col-sm-8">
            <div class="media">
              <a class="pull-left" href="{{ competition.get_absolute_url }}">
                {% if competition.image %}
                  <img class="media-object" src="{{ competition.thumbnail_url }}" alt="{{ competition.name }}" />
                {% else %}
                  <img class="media-object" src="{{ competition.DEFAULT_THUMB }}" alt="{{ competition.name }}" />
                {% endif %}
              </a>
              <div class="media-body">
                <a href="{{ competition.get_absolute_url }}">
                  <h4 class="media-heading">{{ competition.name }}</h4>
                </a>
                {{ competition.description }}
                {% if not competition.is_open and not competition.is_running %}
                  <h4>
                    <span class="label label-info label-lg">
                      Complete
                    </span>
                  </h4>
                {% else %}
                  <h4>
                    <span class="label label-{% if competition.is_open %}success {% else %}danger{% endif %} label-lg">
                      {% if competition.is_open %}
                        Registration Open!
                      {% else %}
                        Registration Closed :(
                      {% endif %}
                    </span>
                  </h4>

                  {% if competition.is_running %}
                  <h4>
                    <span class="label label-{% if competition.is_running %}success {% else %}danger{% endif %} label-lg">
                        In Progress!
                      {% endif %}
                    </span>
                  </h4>
                {% endif %}
              </div>
            </div>
          </div>

          <!-- Right Side -->
          <div class="col-xs-4 hidden-xs hidden-sm">
            <div class="panel panel-info" style="margin-top:20px;">
              <div class="panel-heading">Competition Statistics</div>
              <div class="panel-body">
                <span class="badge">
                  {% registered_users_count competition %}
                </span>
                 Registered Users
                <br>
                <span class="badge">
                  {% freeagent_count competition %}
                </span>
                 Free Agents
                <br>
                <span class="badge">
                  {{ competition.game_set.count }}
                </span>
                 Games Played
              </div>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
      <h2>No competitions, yet.</h2>
    {% endfor %}
  {% include "competition/_paginator.html" with page=page_obj %}
{% endblock %}